---
- name: Ensure SSH configuration settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?\s*{{ item.option }}'
    line: '{{ item.option }} {{ item.value }}'
    state: present
    # backup: yes
  loop:
    - { option: 'PasswordAuthentication', value: 'yes' }
    - { option: 'PermitEmptyPasswords', value: 'no' }
    - { option: 'PermitRootLogin', value: 'no' }
  notify: Restart SSH service

- name: Ensure SSH service is running
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started
  handlers:
    - name: Restart SSH service
      ansible.builtin.systemd:
        name: sshd
        state: restarted